name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Build Linux Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release binary
        run: cargo build --release --package indistocks

      - name: Strip binary
        run: strip target/release/indistocks

      - name: Package binary
        run: |
          mkdir -p indistocks-linux
          cp target/release/indistocks indistocks-linux/
          cp README.md indistocks-linux/ 2>/dev/null || echo "No README found"
          tar czf indistocks-linux-x86_64.tar.gz indistocks-linux/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: indistocks-linux-x86_64
          path: indistocks-linux-x86_64.tar.gz

  build-windows:
    name: Build Windows Binary
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release binary
        run: cargo build --release --package indistocks

      - name: Package binary
        shell: cmd
        run: |
          mkdir indistocks-windows
          copy target\release\indistocks.exe indistocks-windows\
          if exist README.md copy README.md indistocks-windows\
          tar -a -cf indistocks-windows-x86_64.zip indistocks-windows

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: indistocks-windows-x86_64
          path: indistocks-windows-x86_64.zip

  build-macos:
    name: Build macOS Binary
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release binary
        run: cargo build --release --package indistocks

      - name: Strip binary
        run: strip target/release/indistocks

      - name: Package binary
        run: |
          mkdir -p indistocks-macos
          cp target/release/indistocks indistocks-macos/
          cp README.md indistocks-macos/ 2>/dev/null || echo "No README found"
          tar czf indistocks-macos-x86_64.tar.gz indistocks-macos/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: indistocks-macos-x86_64
          path: indistocks-macos-x86_64.tar.gz

  create-release:
    name: Create GitHub Release
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate release notes
        id: release_notes
        run: |
          # Get the previous tag
          PREV_TAG=$(git tag --sort=-v:refname | grep -v "^${{ github.ref_name }}$" | head -n 1)

          if [ -z "$PREV_TAG" ]; then
            echo "First release - including all commits"
            COMMITS=$(git log --pretty=format:"- %s (%h)" ${{ github.ref_name }})
          else
            echo "Generating changelog from $PREV_TAG to ${{ github.ref_name }}"
            COMMITS=$(git log --pretty=format:"- %s (%h)" $PREV_TAG..${{ github.ref_name }})
          fi

          # Write to file to preserve newlines
          cat > release_notes.md <<EOF
          ## Changes

          $COMMITS

          ## Download

          Download the appropriate binary for your platform below.

          ### Linux

          Extract the tarball and run the \`indistocks\` binary:
          \`\`\`bash
          tar xzf indistocks-linux-x86_64.tar.gz
          cd indistocks-linux
          ./indistocks
          \`\`\`

          ### macOS

          Extract the tarball and run the \`indistocks\` binary:
          \`\`\`bash
          tar xzf indistocks-macos-x86_64.tar.gz
          cd indistocks-macos
          ./indistocks
          \`\`\`

          ### Windows

          Extract the zip file and run \`indistocks.exe\`.
          EOF

          cat release_notes.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/**/*.tar.gz
            artifacts/**/*.zip
          body_path: release_notes.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
